-- =====================================================
-- 统一表结构迁移脚本
-- 将 coordination_sessions, workflow_executions 合并为 workflow_sessions
-- 将 coordination_rounds, workflow_execution_messages, agent_messages 合并为 messages
-- =====================================================

-- 1. 创建统一会话表 workflow_sessions
CREATE TABLE IF NOT EXISTS workflow_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 关联信息
    collaboration_id BIGINT NOT NULL,
    task_id BIGINT,
    
    -- 工作流类型
    workflow_type VARCHAR(50) NOT NULL,  -- 'GroupChat' / 'Magentic' / 'Chat'
    orchestration_mode VARCHAR(50),       -- 'RoundRobin' / 'Intelligent' / 'Manager'
    
    -- 执行信息
    status VARCHAR(50) NOT NULL DEFAULT 'running',
    topic TEXT,
    
    -- 冗余元数据（协调者、执行者、工作流参数等）
    metadata TEXT,
    
    -- 统计
    total_rounds INT DEFAULT 0,
    total_messages INT DEFAULT 0,
    
    -- 结果
    conclusion TEXT,
    error_message TEXT,
    
    -- 时间
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_workflow_sessions_collaboration_id ON workflow_sessions(collaboration_id);
CREATE INDEX IF NOT EXISTS idx_workflow_sessions_task_id ON workflow_sessions(task_id);
CREATE INDEX IF NOT EXISTS idx_workflow_sessions_status ON workflow_sessions(status);
CREATE INDEX IF NOT EXISTS idx_workflow_sessions_workflow_type ON workflow_sessions(workflow_type);
CREATE INDEX IF NOT EXISTS idx_workflow_sessions_started_at ON workflow_sessions(started_at);

-- 注释
COMMENT ON TABLE workflow_sessions IS '统一工作流会话表';
COMMENT ON COLUMN workflow_sessions.workflow_type IS '工作流类型: GroupChat(群聊) / Magentic(智能工作流) / Chat(普通聊天)';
COMMENT ON COLUMN workflow_sessions.orchestration_mode IS '协调模式: RoundRobin / Intelligent / Manager';
COMMENT ON COLUMN workflow_sessions.metadata IS '冗余元数据JSON: 协调者、执行者、工作流参数等';

-- 2. 创建统一消息表 messages
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 关联信息
    session_id BIGINT,              -- 关联会话（协调/智能工作流）
    collaboration_id BIGINT,        -- 团队ID（通用）
    task_id BIGINT,                 -- 任务ID
    
    -- 消息类型
    message_type VARCHAR(50),       -- 'coordination' / 'workflow' / 'chat' / 'system'
    round_number INT,               -- 轮次（协调场景）
    step_number INT,                -- 步骤（智能工作流场景）
    
    -- 发送者（冗余）
    from_agent_id BIGINT,
    from_agent_name VARCHAR(100),
    from_agent_role VARCHAR(50),
    
    -- 接收者（点对点场景）
    to_agent_id BIGINT,
    
    -- 内容
    content TEXT,
    thinking_process TEXT,          -- 思考过程
    
    -- 协调特有
    selected_next_speaker VARCHAR(100),
    selection_reason TEXT,
    
    -- 扩展
    metadata TEXT,
    
    -- 时间
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id);
CREATE INDEX IF NOT EXISTS idx_messages_collaboration_id ON messages(collaboration_id);
CREATE INDEX IF NOT EXISTS idx_messages_task_id ON messages(task_id);
CREATE INDEX IF NOT EXISTS idx_messages_from_agent_id ON messages(from_agent_id);
CREATE INDEX IF NOT EXISTS idx_messages_message_type ON messages(message_type);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);

-- 注释
COMMENT ON TABLE messages IS '统一消息表';
COMMENT ON COLUMN messages.message_type IS '消息类型: coordination(协调) / workflow(智能工作流) / chat(聊天) / system(系统)';
COMMENT ON COLUMN messages.round_number IS '轮次（群聊协调场景）';
COMMENT ON COLUMN messages.step_number IS '步骤（智能工作流场景）';

-- 3. 迁移 coordination_sessions 数据到 workflow_sessions（仅当表存在时）
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'coordination_sessions') THEN
        INSERT INTO workflow_sessions (
            collaboration_id, task_id, workflow_type, orchestration_mode, 
            status, topic, metadata, total_rounds, total_messages, 
            conclusion, error_message, started_at, completed_at, created_at
        )
        SELECT 
            collaboration_id, 
            task_id, 
            'GroupChat' as workflow_type,
            orchestration_mode,
            status, 
            topic, 
            metadata, 
            total_rounds, 
            total_messages,
            conclusion, 
            NULL as error_message,
            start_time as started_at, 
            end_time as completed_at, 
            created_at
        FROM coordination_sessions;
    END IF;
END $$;

-- 4. 迁移 workflow_executions 数据到 workflow_sessions（仅当表存在时）
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'workflow_executions') THEN
        INSERT INTO workflow_sessions (
            collaboration_id, task_id, workflow_type, orchestration_mode,
            status, topic, metadata, total_rounds, total_messages,
            conclusion, error_message, started_at, completed_at, created_at
        )
        SELECT 
            collaboration_id,
            task_id,
            workflow_type,
            NULL as orchestration_mode,
            status,
            input as topic,
            NULL as metadata,
            0 as total_rounds,
            0 as total_messages,
            NULL as conclusion,
            error_message,
            started_at,
            completed_at,
            created_at
        FROM workflow_executions;
    END IF;
END $$;

-- 5. 迁移 coordination_rounds 数据到 messages（仅当表存在时）
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'coordination_rounds') THEN
        INSERT INTO messages (
            session_id, collaboration_id, task_id, message_type,
            round_number, step_number, from_agent_id, from_agent_name, from_agent_role,
            to_agent_id, content, thinking_process, selected_next_speaker, selection_reason,
            metadata, created_at
        )
        SELECT 
            cr.session_id,
            cs.collaboration_id,
            cs.task_id,
            'coordination' as message_type,
            cr.round_number,
            NULL as step_number,
            cr.speaker_agent_id as from_agent_id,
            cr.speaker_name as from_agent_name,
            cr.speaker_role as from_agent_role,
            NULL as to_agent_id,
            cr.message_content as content,
            cr.thinking_process,
            cr.selected_next_speaker,
            cr.selection_reason,
            NULL as metadata,
            cr.created_at
        FROM coordination_rounds cr
        LEFT JOIN coordination_sessions cs ON cr.session_id = cs.id;
    END IF;
END $$;

-- 6. 迁移 workflow_execution_messages 数据到 messages（仅当表存在时）
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'workflow_execution_messages') THEN
        INSERT INTO messages (
            session_id, collaboration_id, task_id, message_type,
            round_number, step_number, from_agent_id, from_agent_name, from_agent_role,
            to_agent_id, content, thinking_process, selected_next_speaker, selection_reason,
            metadata, created_at
        )
        SELECT 
            wem.execution_id as session_id,
            we.collaboration_id,
            we.task_id,
            'workflow' as message_type,
            NULL as round_number,
            NULL as step_number,
            NULL as from_agent_id,
            wem.sender as from_agent_name,
            wem.role as from_agent_role,
            NULL as to_agent_id,
            wem.content,
            NULL as thinking_process,
            NULL as selected_next_speaker,
            NULL as selection_reason,
            NULL as metadata,
            wem.timestamp as created_at
        FROM workflow_execution_messages wem
        LEFT JOIN workflow_executions we ON wem.execution_id = we.id;
    END IF;
END $$;

-- 7. 迁移 agent_messages 数据到 messages（仅当表存在时）
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'agent_messages') THEN
        INSERT INTO messages (
            session_id, collaboration_id, task_id, message_type,
            round_number, step_number, from_agent_id, from_agent_name, from_agent_role,
            to_agent_id, content, thinking_process, selected_next_speaker, selection_reason,
            metadata, created_at
        )
        SELECT 
            NULL as session_id,
            collaboration_id,
            NULL as task_id,
            'chat' as message_type,
            NULL as round_number,
            NULL as step_number,
            from_agent_id,
            sender_name as from_agent_name,
            CASE WHEN sender_type = 0 THEN 'user' ELSE 'agent' END as from_agent_role,
            to_agent_id,
            content,
            NULL as thinking_process,
            NULL as selected_next_speaker,
            NULL as selection_reason,
            NULL as metadata,
            created_at
        FROM agent_messages;
    END IF;
END $$;
