-- V46__CreateTaskAgentsTable.sql
-- 创建任务-智能体关联表

CREATE TABLE IF NOT EXISTS task_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES collaboration_tasks(id) ON DELETE CASCADE,
    agent_id BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    role VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(task_id, agent_id)
);

-- 添加索引
CREATE INDEX IF NOT EXISTS idx_task_agents_task_id ON task_agents(task_id);
CREATE INDEX IF NOT EXISTS idx_task_agents_agent_id ON task_agents(agent_id);

-- 添加注释
COMMENT ON TABLE task_agents IS '任务-智能体关联表';
COMMENT ON COLUMN task_agents.task_id IS '任务ID';
COMMENT ON COLUMN task_agents.agent_id IS '智能体ID';
COMMENT ON COLUMN task_agents.role IS '智能体在任务中的角色';
