CREATE TABLE IF NOT EXISTS group_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collaboration_id BIGINT NOT NULL,
    message_type VARCHAR(50) NOT NULL DEFAULT 'chat',
    sender_type VARCHAR(50) NOT NULL DEFAULT 'User',
    from_agent_id BIGINT,
    from_agent_name VARCHAR(100),
    from_agent_role VARCHAR(50),
    from_agent_type VARCHAR(100),
    from_agent_avatar VARCHAR(500),
    model_name VARCHAR(200),
    content TEXT NOT NULL,
    is_mentioned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_messages_collaboration_id ON group_messages(collaboration_id);
CREATE INDEX IF NOT EXISTS idx_group_messages_created_at ON group_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_group_messages_from_agent_id ON group_messages(from_agent_id);

COMMENT ON TABLE group_messages IS '群聊消息表';
COMMENT ON COLUMN group_messages.message_type IS '消息类型: chat(聊天) / system(系统)';
COMMENT ON COLUMN group_messages.sender_type IS '发送者类型: User / Agent';
